twist_mux:
  ros__parameters:
    topics: 
      navigation:
        topic: /diff_cont/cmd_vel_unstamped
        timeout: 0.5
        priority: 10
      ball_tracker:
        topic: cmd_vel_tracker
        timeout: 0.5
        priority: 20
      joystick:
        topic: cmd_vel_joy
        timeout: 0.5
        priority: 100 