twist_mux:
  ros__parameters:
    topics: 
      navigation:
        topic: cmd_vel_keyboard
        timeout: 0.5
        priority: 10
      ball_tracker:
        topic: cmd_vel_tracker
        timeout: 0.5
        priority: 20
      joystick:
        topic: cmd_vel_joy
        timeout: 0.5
        priority: 100 
      explorer:
        topic: cmd_vel
        timeout: 0.5
        priority: 7